title: "DM Nightshade"
description: "Home of D.M. Nightshade"
author:
  name: "Darren M. Nightshade"
  email: "darren@dmnightshade.com"
  url: "https://dmnightshade.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
timezone: America/Los_Angeles
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "DMNightshade"
year : "2019-2020"
